INSERT INTO Client VALUES (1001, 'Disney', 'disney@money.com', 'U.S.A., California, Radiator Springs')
INSERT INTO Client VALUES (1002, 'Universal Studio', 'universal@big.planet.com', 'U.S.A., Texas, Austin')
INSERT INTO Client VALUES (1003, '20th Century Fox', 'centuryFox@searchlight.com', 'U.S.A., California, Radiator Springs')
INSERT INTO Client VALUES (1004, 'Dreamworks', 'dream@works.com', 'Canada, Osaka, Ogre Str.')
INSERT INTO Client VALUES (1005, 'Warner Bros.', 'warner_bros@money.com', 'Romania, Suceava, Stroiesti, str. Aleea')
INSERT INTO Client VALUES (1006, 'HBO', 'hbomax@wb.com', 'Croatia, Dubrovnik, Red Keep Str.')
INSERT INTO Client VALUES (1007, 'Marvel', 'heroes@marvel.com', 'U.S.A., New York, Avengers Tower')

-- INSERT INTO Director(nume_d, varsta_d, adresa_d) VALUES ('Steven Spielberg', 49, 'U.S.A., Aoleo ,Schindler Str.')
-- INSERT INTO Director(nume_d, varsta_d, adresa_d) VALUES ('Tim Burton', 64, 'Burbank, California, Statele Unite')
-- INSERT INTO Director(nume_d, varsta_d, adresa_d) VALUES ('Brad Bird', 65, 'Kalispell, Montana, Statele Unite')
-- INSERT INTO Director(nume_d, varsta_d, adresa_d) VALUES ('Hayao Miyazaki', 81, 'Bunkyo, Tōkyō, Japonia')
-- INSERT INTO Director(nume_d, varsta_d, adresa_d) VALUES ('Vicky Jenson', 62, 'Los Angeles, California, Statele Unite')

INSERT INTO Proiect VALUES (1, 'Spirited Away', 'Film japonez despre Chihiro care ajunge intr-o lume fantastica.', '2023-07-20', 1002, 4)
INSERT INTO Proiect VALUES (2, 'The Incredibles', 'Film animat despre o familie de super-eroi. ', '2024-10-24', 1001, 3)
INSERT INTO Proiect VALUES (3, 'The Dead Bride', 'Productie animata care exploreaza infatisarile iubirii.', '2025-09-16', 1003, 2)
INSERT INTO Proiect VALUES (4, 'Shrek', 'Un capcaun care traieste intr-o mlastina.', '2024-07-20', 1005, 5)
INSERT INTO Proiect VALUES (5, 'Spirit: Stallion of Cimarron', 'Spiritul vestului surprins prin intermediul unui armasar', '2023-08-19', 1003, 1)
INSERT INTO Proiect VALUES (6, 'Howls Moving Castle', 'Film japonez despre o fata care ajunge in castelul unui vrajitor.', '2022-12-04', 1001, 4)
INSERT INTO Proiect VALUES (7, 'The Lego Movie', 'Film animat despre omuleti LEGO', '2023-04-01', 1007, 1)
INSERT INTO Proiect VALUES (8, 'Coco', 'Un baietel care readuce muzica intr-o familie pentru care muzica e taboo.', '2025-03-13', 1005, 5)

INSERT INTO Scena VALUES (11, 60, '2022-11-04', 1000, 1)
INSERT INTO Scena VALUES (21, 120, '2023-09-14', 2000, 2)
INSERT INTO Scena VALUES (22, 240, '2024-01-25', 2322, 2)
INSERT INTO Scena VALUES (23, 20, '2024-04-06', 220, 2)
INSERT INTO Scena VALUES (24, 70, '2023-11-25', 750, 2)
INSERT INTO Scena VALUES (31, 160, '2024-04-03', 2800, 3)
INSERT INTO Scena VALUES (51, 45, '2022-12-04', 1200, 5)
INSERT INTO Scena VALUES (81, 30, '2024-07-06', 700, 8)
INSERT INTO Scena VALUES (61, 95, '2022-11-10', 1100, 6)
INSERT INTO Scena VALUES (62, 10, '2022-11-27', 300, 6)
INSERT INTO Scena VALUES (12, 105, '2022-12-28', 1100, 1)
INSERT INTO Scena VALUES (32, 200, '2024-10-12', 1200, 3)
INSERT INTO Scena VALUES (41, 190, '2023-05-15', 1300, 4)
INSERT INTO Scena VALUES (71, 160, '2022-11-27', 1400, 7)
INSERT INTO Scena VALUES (72, 145, '2023-02-28', 1500, 7)
INSERT INTO Scena VALUES (73, 25, '2023-04-15', 340, 7)

INSERT INTO Element VALUES (1, 'www.elements-for-movies.com', 'Copaci', 'O colectie de copaci de foioase si conifere.')
INSERT INTO Element VALUES (2, 'intern', 'Stanci', 'Stanci de diferite forme cu scop de ornare a cadrelor')
INSERT INTO Element VALUES (3, 'www.elements-for-movies.com', 'Cladiri medievale', 'O colectie de cladiri cu aspect medieval.')
INSERT INTO Element VALUES (4, 'www.elements-for-movies.com', 'Cladiri moderne', 'O colectie de cladiri cu aspect modern.')
INSERT INTO Element VALUES (5, 'intern', 'Copaci', 'Copaci: salcie, brad, cires, mar')
INSERT INTO Element VALUES (6, 'www.anielements.com', 'Monstrii', 'Diferite tipuri de monstrii, aspect respingator, full-color')

INSERT INTO TipArtist VALUES (1, 'Concept Art')
INSERT INTO TipArtist VALUES (2, 'Colorare')
INSERT INTO TipArtist VALUES (3, 'Animare')
INSERT INTO TipArtist VALUES (4, 'Audio')
INSERT INTO TipArtist VALUES (5, 'Modelare')

INSERT INTO Supervizor VALUES (1, 'John Graves')
INSERT INTO Supervizor VALUES (2, 'Matthew Smith')
INSERT INTO Supervizor VALUES (3, 'Mircea Popescu')
INSERT INTO Supervizor VALUES (4, 'Natalia Lackless')

-- INSERT INTO Artist VALUES ('Costel Fare', 2, 1)
-- INSERT INTO Artist VALUES ('Dorel Hare', 1, 2)
-- INSERT INTO Artist VALUES ('Marcel Bare', 1, 3)
-- INSERT INTO Artist VALUES ('Maria Ioana', 5, 4)
-- INSERT INTO Artist VALUES ('Dorian Popa', 4, 1)
-- INSERT INTO Artist VALUES ('Bahoi', 2, 2)
-- INSERT INTO Artist VALUES ('Mihaela Tas', 2, 3)
-- INSERT INTO Artist VALUES ('Codin Pop', 3, 4)
-- INSERT INTO Artist VALUES ('Ramona Pop', 3, 1)
-- INSERT INTO Artist VALUES ('Codrin Bradea', 1, 2)
-- INSERT INTO Artist VALUES ('John Graves', 4, 3)
-- INSERT INTO Artist VALUES ('Natalia Lackless', 2, 3)
-- INSERT INTO Artist VALUES ('Matthew Smith', 5, 3)

INSERT INTO Atribuire VALUES (11, 1)
INSERT INTO Atribuire VALUES (11, 2)
INSERT INTO Atribuire VALUES (11, 3)
INSERT INTO Atribuire VALUES (12, 2)
INSERT INTO Atribuire VALUES (12, 1)
INSERT INTO Atribuire VALUES (71, 2)
INSERT INTO Atribuire VALUES (71, 4)
INSERT INTO Atribuire VALUES (72, 6)
INSERT INTO Atribuire VALUES (73, 6)
INSERT INTO Atribuire VALUES (73, 4)
INSERT INTO Atribuire VALUES (21, 1)
INSERT INTO Atribuire VALUES (21, 2)
INSERT INTO Atribuire VALUES (21, 5)
INSERT INTO Atribuire VALUES (22, 3)
INSERT INTO Atribuire VALUES (22, 1)
INSERT INTO Atribuire VALUES (23, 3)
INSERT INTO Atribuire VALUES (23, 5)
INSERT INTO Atribuire VALUES (24, 2)
INSERT INTO Atribuire VALUES (31, 4)
INSERT INTO Atribuire VALUES (32, 5)
INSERT INTO Atribuire VALUES (32, 4)
INSERT INTO Atribuire VALUES (41, 1)
INSERT INTO Atribuire VALUES (41, 5)
INSERT INTO Atribuire VALUES (51, 4)
INSERT INTO Atribuire VALUES (61, 6)
INSERT INTO Atribuire VALUES (62, 6)
INSERT INTO Atribuire VALUES (62, 3)
INSERT INTO Atribuire VALUES (81, 1)
INSERT INTO Atribuire VALUES (81, 2)
INSERT INTO Atribuire VALUES (81, 6)

INSERT INTO Task VALUES (2, 11)
INSERT INTO Task VALUES (6, 11)
INSERT INTO Task VALUES (8, 11)
INSERT INTO Task VALUES (4, 11)
INSERT INTO Task VALUES (3, 11)
INSERT INTO Task VALUES (2, 12)
INSERT INTO Task VALUES (7, 12)
INSERT INTO Task VALUES (5, 12)
INSERT INTO Task VALUES (1, 21)
INSERT INTO Task VALUES (10, 21)
INSERT INTO Task VALUES (9, 22)
INSERT INTO Task VALUES (13, 22)
INSERT INTO Task VALUES (10, 23)
INSERT INTO Task VALUES (1, 23)
INSERT INTO Task VALUES (9, 23)
INSERT INTO Task VALUES (3, 24)
INSERT INTO Task VALUES (8, 24)
INSERT INTO Task VALUES (2, 31)
INSERT INTO Task VALUES (3, 31)
INSERT INTO Task VALUES (1, 31)
INSERT INTO Task VALUES (3, 32)
INSERT INTO Task VALUES (5, 32)
INSERT INTO Task VALUES (3, 41)
INSERT INTO Task VALUES (1, 41)
INSERT INTO Task VALUES (4, 41)
INSERT INTO Task VALUES (10, 51)
INSERT INTO Task VALUES (2, 51)
INSERT INTO Task VALUES (8, 61)
INSERT INTO Task VALUES (9, 62)
INSERT INTO Task VALUES (12, 62)
INSERT INTO Task VALUES (11, 71)
INSERT INTO Task VALUES (3, 71)
INSERT INTO Task VALUES (2, 73)
INSERT INTO Task VALUES (10, 72)
INSERT INTO Task VALUES (9, 72)
INSERT INTO Task VALUES (3, 81)
INSERT INTO Task VALUES (6, 81)
INSERT INTO Task VALUES (9, 81)
INSERT INTO Task VALUES (5, 81)
INSERT INTO Task VALUES (4, 81)

